---
- name: "Updating /etc/apt/sources.list"
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  notify: Updating apt cache

- name: "Include release change"
  ansible.builtin.include_tasks: release_change.yml
  when: apt_sources_remove_release_change_alert | bool

- name: "Include non-free firware alert"
  ansible.builtin.include_tasks: bookworm_firmware.yml
  when: apt_sources_remove_bookworm_firmare_alert | bool

- name: "Install nodoc options"
  ansible.builtin.template:
    src: nodoc.j2
    dest: /etc/dpkg/dpkg.cfg.d/01_nodoc
    mode: '0644'
  when: apt_sources_exclude_man | bool or apt_sources_include_locales | length > 0

- name: "Disable apt caches"
  ansible.builtin.template:
    src: nocache.j2
    dest: /etc/apt/apt.conf.d/02_nocache
    mode: '0644'
  when: apt_sources_disable_caches | bool

- name: "Compress indexes"
  ansible.builtin.template:
    src: compress_indexes.j2
    dest: /etc/apt/apt.conf.d/02_compress_indexes
    mode: '0644'
  when: apt_sources_compress_indexes | bool

- name: "Ignore additional or suggested packages"
  ansible.builtin.template:
    src: no_additional.j2
    dest: /etc/apt/apt.conf.d/02_no_additional
    mode: '0644'
  when: apt_sources_ignore_additional | bool

- name: "Force connection with ipv4"
  ansible.builtin.template:
    src: templates/force-ipv4.j2
    dest: /etc/apt/apt.conf.d/99_force-ipv4
    mode: '0644'
  when: apt_sources_force_ipv4 | bool
